
spring:
  datasource:
    url: jdbc:postgresql://localhost/restaurant
    username: postgres
    password: felixmaina
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform:  org.hibernate.dialect.PostgreSQLDialect

# Hibernate=ddl auto (create, create-drop, validate, update)
server:
  port: 8081
